// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AnalyticalWays.DataProcessor.Model
{
    public partial class AnalyticalWaysTestDbContext : DbContext
    {
        public AnalyticalWaysTestDbContext()
        {
        }

        public AnalyticalWaysTestDbContext(DbContextOptions<AnalyticalWaysTestDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<StockInformation> StockInformation { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<StockInformation>(entity =>
            {
                entity.HasKey(e => new { e.Pos, e.Product, e.StockDate });

                entity.Property(e => e.Pos)
                    .HasColumnName("pos")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Product)
                    .HasColumnName("product")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StockDate)
                    .HasColumnName("stockDate")
                    .HasColumnType("date");

                entity.Property(e => e.Stock).HasColumnName("stock");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}