// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AnalyticalWays.DataProcessor.Model
{
    public partial class StockInformation
    {
        public string Pos { get; set; }
        public string Product { get; set; }
        public DateTime StockDate { get; set; }
        public int Stock { get; set; }
    }
}